import os
import json
import time
from dotenv import load_dotenv
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# Load environment variables from .env
load_dotenv()

# Spotify credentials
CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI", "http://127.0.0.1:8888/callback")

# Scopes needed for the script
SCOPES = [
    "playlist-modify-public",
    "playlist-modify-private",
    "playlist-read-private",
    "playlist-read-collaborative",
    "user-read-private",
    "user-library-read"
]

def get_spotify_client():
    """Initialize and authenticate the Spotify client."""
    if not CLIENT_ID or not CLIENT_SECRET:
        print("Error: SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET must be set in a .env file.")
        exit(1)

    # Use a consistent cache path to avoid multiple browser prompts
    cache_path = os.path.join(os.path.dirname(__file__), ".cache", ".spotify_token")
    os.makedirs(os.path.dirname(cache_path), exist_ok=True)

    auth_manager = SpotifyOAuth(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        redirect_uri=REDIRECT_URI,
        scope=" ".join(SCOPES),
        cache_path=cache_path,
        show_dialog=True,
        open_browser=True
    )

    # Check if we already have a valid token
    token_info = auth_manager.get_cached_token()
    if not token_info:
        print("\n" + "!" * 60)
        print("AUTHENTICATION REQUIRED")
        print("A browser tab will open to authorize the application.")
        print("If it doesn't open automatically, please check your console for a link.")
        print("!" * 60 + "\n")

    return spotipy.Spotify(auth_manager=auth_manager)

def sync_playlists(json_path):
    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found. Run classify_songs.py first.")
        return

    sp = get_spotify_client()

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        playlists_data = data.get('playlists', [])

    user_info = sp.current_user()
    user_id = user_info['id']
    print(f"Authenticated as: {user_info['display_name']} ({user_id})")

    # Get current user's playlists to avoid duplicates
    current_playlists = []
    results = sp.current_user_playlists()
    current_playlists.extend(results['items'])
    while results['next']:
        results = sp.next(results)
        current_playlists.extend(results['items'])
    
    existing_names = {pl['name']: pl['id'] for pl in current_playlists}

    for pl_data in playlists_data:
        name = pl_data['name']
        description = pl_data.get('description', 'Generated by Spotify Liked Songs Classifier')
        track_uris = pl_data.get('track_uris', [])

        if name in existing_names:
            print(f"Playlist '{name}' already exists. Skipping creation.")
            playlist_id = existing_names[name]
        else:
            print(f"Creating playlist: {name}")
            try:
                # Use the new February 2026 /me/playlists endpoint
                payload = {
                    "name": name,
                    "public": False,
                    "description": description
                }
                new_pl = sp._post("me/playlists", payload=payload)
                playlist_id = new_pl['id']
                time.sleep(1) # Small delay to be gentle with the API
            except Exception as e:
                print(f"Failed to create playlist '{name}': {e}")
                # Log more details if possible
                if hasattr(e, 'http_status'):
                    print(f"  HTTP Status: {e.http_status}")
                continue

        # Add tracks in batches of 100
        print(f"  Adding {len(track_uris)} tracks to '{name}'...")
        for i in range(0, len(track_uris), 100):
            batch = track_uris[i : i + 100]
            sp.playlist_add_items(playlist_id, batch)
            time.sleep(0.5) # Avoid hitting rate limits

    print("\nSynchronization complete!")

if __name__ == "__main__":
    sync_playlists("output/playlists.json")
