import os
import json
import time
from dotenv import load_dotenv
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# Load environment variables from .env
load_dotenv()

CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI", "http://127.0.0.1:8888/callback")

if not CLIENT_ID or not CLIENT_SECRET:
    print("Error: SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET must be set in a .env file.")
    exit(1)

# Initialize Spotify client
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
    scope="playlist-modify-public"
))

def sync_playlists(json_path):
    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found. Run classify_songs.py first.")
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        playlists_data = json.load(f)

    user_info = sp.current_user()
    user_id = user_info['id']
    print(f"Authenticated as: {user_info['display_name']} ({user_id})")

    # Get current user's playlists to avoid duplicates (optional, could be improved)
    current_playlists = []
    results = sp.current_user_playlists()
    current_playlists.extend(results['items'])
    while results['next']:
        results = sp.next(results)
        current_playlists.extend(results['items'])
    
    existing_names = {pl['name']: pl['id'] for pl in current_playlists}

    for pl_data in playlists_data:
        name = pl_data['name']
        description = pl_data.get('description', 'Generated by Spotify Liked Songs Classifier')
        track_uris = [track['uri'] for track in pl_data['tracks']]

        if name in existing_names:
            print(f"Playlist '{name}' already exists. Skipping creation.")
            playlist_id = existing_names[name]
        else:
            print(f"Creating playlist: {name}")
            new_pl = sp.user_playlist_create(user=user_id, name=name, public=True, description=description)
            playlist_id = new_pl['id']

        # Add tracks in batches of 100
        print(f"  Adding {len(track_uris)} tracks to '{name}'...")
        for i in range(0, len(track_uris), 100):
            batch = track_uris[i : i + 100]
            sp.playlist_add_items(playlist_id, batch)
            time.sleep(0.5) # Avoid hitting rate limits

    print("\nSynchronization complete!")

if __name__ == "__main__":
    sync_playlists("output/playlists.json")
